//AUTH TYPES
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_LOADING = 'SET_LOADING';
export const SET_LOGIN_MODAL = 'SET_LOGIN_MODAL'
export const SET_SIGNUP_MODAL = 'SET_SIGNUP_MODAL'
export const SET_BRANCH_MODAL = 'SET_BRANCH_MODAL'
export const SET_ACCOUNT_BRANCH = 'SET_ACCOUNT_BRANCH'
export const SAVE_BRANCH = 'SAVE_BRANCH'

//ALERT TYPES
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'


//SEARCH TYPES
export const TERM_ADDED = 'TERM_ADDED'
export const TERM_FAIL = 'TERM_FAIL'
export const TERM_GET = 'TERM_GET'
export const SET_TERM_TEXT = 'SET_TERM_TEXT'


//INFLUENCERS
export const GET_INFLUENCERS = 'GET_INFLUENCERS'
export const GET_INFLUENCERS_ERROR = 'GET_INFLUENCERS_ERROR'